/*
 * generated by Xtext 2.10.0
 */
package org.apache.thrift


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IDLStandaloneSetup extends IDLStandaloneSetupGenerated {

	def static void doSetup() {
		new IDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
